apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfs
      node: node2
  template:
    metadata:
      labels:
        app: sfs
        node: node2
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      containers:
        - name: sfs-container
          image: brentjohnson/smartfoxserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9933
            - containerPort: 8080
---
# Service cho pod app-0 → nodePort 30001
apiVersion: v1
kind: Service
metadata: 
  name: np-node2
spec:
  type: NodePort
  selector:
    app: sfs
    node: node2
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: mobile
      protocol: TCP
      port: 9933
      targetPort: 9933
      nodePort: 30001